frontend/controllers/RequestController.php
<?php


namespace frontend\controllers;


use core\entities\Organization;
use core\entities\Request;
use core\forms\RequestForm;
use core\helpers\OrgHelper;
use core\helpers\RequestHelper;
use core\parser\jobs\LoadJob;
use core\parser\jobs\ParseJob;
use yii\data\ActiveDataProvider;
use yii\helpers\VarDumper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

class RequestController extends Controller
{

    public function actionIndex()
    {

        $dataProvider = new ActiveDataProvider([
            'query' => Request::find(),
            'sort' => [
                'defaultOrder' => ['id' => SORT_DESC]
            ]
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }


    public function actionCreate()
    {
        $form = new RequestForm();

        if ($form->load(\Yii::$app->request->post()) && $form->validate()) {
            $request = Request::create($form);
            $request->save();

            \Yii::$app->queue->push(new ParseJob([
                'id' => $request->id
            ]));

            return $this->redirect(['index']);
        }

        return $this->render('create', [
            'model' => $form,
        ]);
    }

    public function actionOgrn($id)
    {
        $model = Organization::find()->where(['id' => $id])->one();
        if (!$model) {
            throw new NotFoundHttpException('Организация не найдена');
        }

        if ($model->load(\Yii::$app->request->post())) {
            $model->status = OrgHelper::STATUS_WAIT;
            $model->save();

            \Yii::$app->queue->push(new LoadJob([
                'ids' => [$model->id]
            ]));
        }

        return $this->redirect(\Yii::$app->request->referrer);
    }

    public function actionSetOgrn($id)
    {
        $model = $this->findModel($id);
        $dataProvider = new ActiveDataProvider([
            'query' => $model->getRequests()->where(['ogrn' => ''])->with('orgRequests'),
        ]);

        return $this->render('view', [
            'model' => $model,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionView($id)
    {
        $model = $this->findModel($id);
        $dataProvider = new ActiveDataProvider([
            'query' => $model->getRequests()->with('orgRequests'),
        ]);

        return $this->render('view', [
            'model' => $model,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionDownload($id)
    {
        $model = $this->findModel($id);
        $query = Organization::find();
        if ($id) {
            $query->select(['org_request.*', 'organization.*']);
            $query->joinWith(['orgRequest' => function ($query) use ($id){
                return $query->where(['request_id' => $id]);

            }]);

        }

        $file = \Yii::createObject([
            'class' => 'codemix\excelexport\ExcelFile',
            'sheets' => [
                'Person' => [
                    'class' => 'codemix\excelexport\ActiveExcelSheet',
                    'query' => $query,
                    'types' => ['s', 's', 's', 's', 's', 's', 's'],
                    'attributes' => [
                        'orgRequest.number',
                        'orgRequest.date',
                        'orgRequest.name',
                        'orgRequest.comment',
                        'orgRequest.sum',
                        'ogrn',
                        'name',
                        'address',
                        'email',
                        'phone',
                        'chief'
                    ],
                ]
            ]
        ]);
        $file->send('Выборка '. RequestHelper::getTypeValue($model->type). ' от ' . date('d.m.Y H:i:s', $model->created_at) . '.xlsx');
    }

    public function actionDelete($id)
    {
        $model = $this->findModel($id);

        $model->delete();

        return $this->redirect(['index']);
    }


    /**
     * @param $id
     * @return array|Request|null|\yii\db\ActiveRecord
     * @throws NotFoundHttpException
     */
    private function findModel($id)
    {
        $model = Request::find()->where(['id' => $id])->one();
        if (!$model) {
            throw new NotFoundHttpException('Выборка не найдена');
        }

        return $model;
    }


}

frontend/views/request/_form.php
<?php

use core\entities\Organization;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model Organization */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="account-form">

    <?php $form = ActiveForm::begin([
        'action' => ['request/ogrn', 'id' => $model->id],
        'method' => 'post'
    ]); ?>

    <?= $form->field($model, 'ogrn')->label(false)->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton('Обновить', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/request/create.php
<?php

use core\helpers\RequestHelper;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use yii\jui\DatePicker;

/* @var $this yii\web\View */
/* @var $model core\forms\RequestForm */

$this->title = 'Создание выборки';
$this->params['breadcrumbs'][] = ['label' => 'Поисковые выборки', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="request-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php $form = ActiveForm::begin(); ?>
    <?= $form->field($model, 'sum')->textInput() ?>

    <?= $form->field($model, 'type')->dropDownList(RequestHelper::getTypeList()) ?>

    <h4>Дата регистрации</h4>
    <div class="row">
        <div class="col-md-6">
            <?= $form->field($model, 'date_from')->widget(DatePicker::className(), [
                'language' => 'ru',
                'dateFormat' => 'yyyy-MM-dd',
                'options' => [
                    'class' => 'form-control'
                ]
            ]) ?>
        </div>
        <div class="col-md-6">
            <?= $form->field($model, 'date_to')->widget(DatePicker::className(), [
                'language' => 'ru',
                'dateFormat' => 'yyyy-MM-dd',
                'options' => [
                    'class' => 'form-control'
                ]
            ]) ?>
        </div>
    </div>

    <div class="form-group">
        <?= Html::submitButton('Найти', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/request/index.php
<?php

use core\entities\Request;
use core\helpers\RequestHelper;
use yii\grid\GridView;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Поисковые выборки';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="account-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Сделать выборку', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            'id',
            [
                'attribute' => 'created_at',
                'format' => 'raw',
                'value' => function (Request $request) {
                    return Html::a(\Yii::$app->formatter->asDatetime($request->created_at),
                        ['view', 'id' => $request->id]);
                }
            ],
            'sum',
            [
                'attribute' => 'type',
                'format' => 'raw',
                'value' => function (Request $request) {
                    return (string)RequestHelper::getTypeValue($request->type);
                }
            ],

            [
                'header' => 'Дата регистрации',
                'format' => 'raw',
                'value' => function (Request $request) {
                    return 'с ' . $request->date_from . ' по ' . $request->date_to;
                }
            ],
            [
                'header' => 'Найдено / Загружено',
                'format' => 'raw',
                'value' => function (Request $request) {
                    return count($request->requests) . ' / ' . count($request->completeRequests);
                }
            ],
            [
                'attribute' => 'status',
                'format' => 'raw',
                'value' => function (Request $model) {
                    return Html::tag('span', RequestHelper::getStatusLabel($model->status), [
                        'class' => 'label ' . RequestHelper::getStatusClass($model->status)
                    ]);
                }
            ],

            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{view} {download} {delete}',
                'buttons' => [
                    'download' => function ($link) {
                        return Html::a('<span class="glyphicon glyphicon-save"></span>',
                            $link, [
                                'title' => \Yii::t('yii', 'Скачать'),
                                'data-pjax' => '0',
                            ]);
                    },
                ]
            ],
        ],
    ]); ?>
</div>

frontend/views/request/view.php
<?php

use core\entities\Organization;
use core\entities\Request;
use yii\grid\GridView;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $model Request */

$this->title = 'Выборка от ' . date('d.m.Y H:i:s', $model->created_at);
$this->params['breadcrumbs'][] = ['label' => 'Поисковые выборки', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="account-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('ОГРН', ['request/set-ogrn', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Скачать', ['request/download', 'id' => $model->id], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            [
                'attribute' => 'orgRequests.number',
                'value' => function (Organization $org) use ($model) {
                    foreach ($org->orgRequests as $orgRequest) {
                        if ($orgRequest->request_id == $model->id) {
                            return $orgRequest->number;
                        }
                    }
                    return null;
                }
            ],
            [
                'attribute' => 'orgRequests.date',
                'value' => function (Organization $org) use ($model) {
                    foreach ($org->orgRequests as $orgRequest) {
                        if ($orgRequest->request_id == $model->id) {
                            return Yii::$app->formatter->asDate($orgRequest->date, 'short');
                        }
                    }
                    return null;
                }
            ],
            [
                'attribute' => 'orgRequests.name',
                'value' => function (Organization $org) use ($model) {
                    foreach ($org->orgRequests as $orgRequest) {
                        if ($orgRequest->request_id == $model->id) {
                            return $orgRequest->name;
                        }
                    }
                    return null;
                }
            ],
            [
                'attribute' => 'orgRequests.comment',
                'value' => function (Organization $org) use ($model) {
                    foreach ($org->orgRequests as $orgRequest) {
                        if ($orgRequest->request_id == $model->id) {
                            return $orgRequest->comment;
                        }
                    }
                    return null;
                }
            ],
            [
                'attribute' => 'orgRequests.sum',
                'value' => function (Organization $org) use ($model) {
                    foreach ($org->orgRequests as $orgRequest) {
                        if ($orgRequest->request_id == $model->id) {
                            return Yii::$app->formatter->asCurrency($orgRequest->sum);
                        }
                    }
                    return null;
                }
            ],
            [
                'attribute' => 'ogrn',
                'format' => 'raw',
                'value' => function (Organization $model) {
                    return $model->ogrn ?
                        Html::a($model->ogrn, 'https://casebook.ru/#side/info/' . $model->ogrn, [
                            'target' => '_blank'
                        ]) :
                        Yii::$app->view->render('_form', ['model' => $model]);
                }
            ],

            [
                'attribute' => 'name',
                'format' => 'raw',
                'value' => function (Organization $model) {
                    return ($model->ogrn ? $model->name :
                            Html::a($model->name, 'http://www.rusprofile.ru/search?query='.$model->name, [
                                'target' => '_blank'
                            ])) .
                        "<br><br>" . $model->address;
                }
            ],
            'email',
            'phone',
            'chief',
//            [
//                'attribute' => 'status',
//                'format' => 'raw',
//                'value' => function (Organization $model) {
//                    return Html::tag('span', OrgHelper::getStatusLabel($model->status), [
//                        'class' => 'label ' . OrgHelper::getStatusClass($model->status)
//                    ]);
//                }
//            ],
        ],
    ]); ?>
</div>