frontend/controllers/RequestController.php
<?php


namespace frontend\controllers;


use core\entities\Organization;
use core\entities\Request;
use core\forms\RequestForm;
use core\helpers\OrgHelper;
use core\helpers\RequestHelper;
use core\parser\jobs\LoadJob;
use core\parser\jobs\ParseJob;
use yii\data\ActiveDataProvider;
use yii\helpers\VarDumper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

class RequestController extends Controller
{

    public function actionIndex()
    {

        $dataProvider = new ActiveDataProvider([
            'query' => Request::find(),
            'sort' => [
                'defaultOrder' => ['id' => SORT_DESC]
            ]
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }


    public function actionCreate()
    {
        $form = new RequestForm();

        if ($form->load(\Yii::$app->request->post()) && $form->validate()) {
            $request = Request::create($form);
            $request->save();

            \Yii::$app->queue->push(new ParseJob([
                'id' => $request->id
            ]));

            return $this->redirect(['index']);
        }

        return $this->render('create', [
            'model' => $form,
        ]);
    }

    public function actionOgrn($id)
    {
        $model = Organization::find()->where(['id' => $id])->one();
        if (!$model) {
            throw new NotFoundHttpException('Организация не найдена');
        }

        if ($model->load(\Yii::$app->request->post())) {
            $model->status = OrgHelper::STATUS_WAIT;
            $model->save();

            \Yii::$app->queue->push(new LoadJob([
                'ids' => [$model->id]
            ]));
        }

        return $this->redirect(\Yii::$app->request->referrer);
    }

    public function actionSetOgrn($id)
    {
        $model = $this->findModel($id);
        $dataProvider = new ActiveDataProvider([
            'query' => $model->getRequests()->where(['ogrn' => ''])->with('orgRequests'),
        ]);

        return $this->render('view', [
            'model' => $model,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionView($id)
    {
        $model = $this->findModel($id);
        $dataProvider = new ActiveDataProvider([
            'query' => $model->getRequests()->with('orgRequests'),
        ]);

        return $this->render('view', [
            'model' => $model,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionDownload($id)
    {
        $model = $this->findModel($id);
        $query = Organization::find();
        if ($id) {
            $query->select(['org_request.*', 'organization.*']);
            $query->joinWith(['orgRequest' => function ($query) use ($id){
                return $query->where(['request_id' => $id]);

            }]);

        }

        $file = \Yii::createObject([
            'class' => 'codemix\excelexport\ExcelFile',
            'sheets' => [
                'Person' => [
                    'class' => 'codemix\excelexport\ActiveExcelSheet',
                    'query' => $query,
                    'types' => ['s', 's', 's', 's', 's', 's', 's'],
                    'attributes' => [
                        'orgRequest.number',
                        'orgRequest.date',
                        'orgRequest.name',
                        'orgRequest.comment',
                        'orgRequest.sum',
                        'ogrn',
                        'name',
                        'address',
                        'email',
                        'phone',
                        'chief'
                    ],
                ]
            ]
        ]);
        $file->send('Выборка '. RequestHelper::getTypeValue($model->type). ' от ' . date('d.m.Y H:i:s', $model->created_at) . '.xlsx');
    }

    public function actionDelete($id)
    {
        $model = $this->findModel($id);

        $model->delete();

        return $this->redirect(['index']);
    }


    /**
     * @param $id
     * @return array|Request|null|\yii\db\ActiveRecord
     * @throws NotFoundHttpException
     */
    private function findModel($id)
    {
        $model = Request::find()->where(['id' => $id])->one();
        if (!$model) {
            throw new NotFoundHttpException('Выборка не найдена');
        }

        return $model;
    }


}

frontend/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use frontend\assets\AppAsset;
use common\widgets\Alert;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    $menuItems = [
        ['label' => 'Поиск', 'url' => ['/request/index']],
        ['label' => 'Аккаунты', 'url' => ['/account/index']],
    ];
//    if (Yii::$app->user->isGuest) {
//        $menuItems[] = ['label' => 'Signup', 'url' => ['/site/signup']];
//        $menuItems[] = ['label' => 'Login', 'url' => ['/site/login']];
//    } else {
//        $menuItems[] = '<li>'
//            . Html::beginForm(['/site/logout'], 'post')
//            . Html::submitButton(
//                'Logout (' . Yii::$app->user->identity->username . ')',
//                ['class' => 'btn btn-link logout']
//            )
//            . Html::endForm()
//            . '</li>';
//    }
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menuItems,
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; <?= Html::encode(Yii::$app->name) ?> <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>